### ISSUE TITLE
Streamline task descriptions

### ISSUE THREAD

**Issue by rcannood** [openproblems-bio/website#12]
When #9 is merged, we need to add description pages for the different subtasks. We can probably import them from `openproblems-bio/openproblems`, but I notice that there is a difference between the documentation provided there vs. the documentation written on this website. I suppose we should merge the two and align the descriptions between both repositories? It'd be nice if the README's could automatically be imported into the website by means of a script.

* [ ] Merge [`openproblems/openproblems/tasks/label_projection/README.md`](https://github.com/openproblems-bio/openproblems/tree/main/openproblems/tasks/label_projection) and [`website/content/results/label_projection.md`](https://github.com/openproblems-bio/website/blob/main/content/results/label_projection.md).
* [ ] Merge [`openproblems/openproblems/tasks/multimodal_data_integration/README.md`](https://github.com/openproblems-bio/openproblems/tree/main/openproblems/tasks/multimodal_data_integration) and [`website/content/results/multimodal_data_integration.md`](https://github.com/openproblems-bio/website/blob/main/content/results/multimodal_data_integration.md).
* [ ] Import [`openproblems/openproblems/tasks/_batch_integration/batch_integration_graph`](https://github.com/openproblems-bio/openproblems/tree/main/openproblems/tasks/_batch_integration/batch_integration_graph)
* [ ] Import [`openproblems/openproblems/tasks/denoising`](https://github.com/openproblems-bio/openproblems/tree/main/openproblems/tasks/denoising)
* [ ] Import [`openproblems/openproblems/tasks/dimensionality_reduction`](https://github.com/openproblems-bio/openproblems/tree/main/openproblems/tasks/dimensionality_reduction)
* [ ] Import [`openproblems/openproblems/tasks/regulatory_effect_prediction`](https://github.com/openproblems-bio/openproblems/tree/main/openproblems/tasks/regulatory_effect_prediction)

**Comment by scottgigante** [comment]
I agree, it would be nice to import them automatically. Important to note that the information needed on the website and the information needed on the github are slightly different -- one is for devs, one is for users.

**Comment by scottgigante** [comment]
Might be that the website md should be a subset of the github readme (excluding the technical implementation details)
