### ISSUE TITLE
Colour funkyheatmap by rank, not score

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/website#150]
When scores are similar it's hard to see the differences in ranking. Ideal: keep size by absolute score, colour by rank. cc @LuckyMD

**Comment by scottgigante-immunai** [comment]
@LuckyMD you originally asked for this -- how do you feel about it now that we have the sorting function?

**Comment by LuckyMD** [comment]
I think it would still be very useful. I would like to digest this information for other metrics/datasets when i am sorting by another one as well.

**Comment by rcannood** [comment]
The current implementation allows colouring by rank by checking a box :)
