### ISSUE TITLE
bibliography ref links open in new tab

### ISSUE THREAD

**Issue by KaiWaldrant** [openproblems-bio/website#180]
@rcannood looks like you are adding the `target=_blank` on purpose so this is intentional behaviour ?

**Comment by rcannood** [comment]
I think this is indeed the most practical behaviour, so that you can browse the results and open some references without going away from the main article.

At any rate, I think the actual most useful behaviour would be to create a hover with the citation details (which is the default in quarto).

**Comment by rcannood** [comment]
Oops, didn't mean to close -_-

**Comment by KaiWaldrant** [comment]
Reopen as a enhancement for future release

**Comment by KaiWaldrant** [comment]
This has already been implemented.
