### ISSUE TITLE
Temporarily revert dark mode

### ISSUE THREAD

**Issue by rcannood** [openproblems-bio/website#182]
I'm strongly considering moving the dark mode out of the main branch and moving it into a separate branch, because it results in a lot of rendering artifacts (not just on this page). Once these are solved in properly, we can merge it back into main. @scottgigante-immunai wdyt?

_Originally posted by @rcannood in https://github.com/openproblems-bio/website/pull/172#pullrequestreview-1336071920_

**Comment by rcannood** [comment]
- [ ] Labels are dark in [FH](https://main--openproblems.netlify.app/results/batch_integration_embed/) when not in dark mode:
![Screenshot from 2023-03-13 12-57-21](https://user-images.githubusercontent.com/553642/224695322-d4d24963-e972-4052-a16e-05e5fd08506c.png)

- [ ] [FH](https://main--openproblems.netlify.app/results/batch_integration_embed/) doesn't have a dark mode:
![Screenshot from 2023-03-13 12-58-15](https://user-images.githubusercontent.com/553642/224695486-69ac2b25-7a30-4c48-85ba-2677583a0edf.png)

- [ ] [NeurIPS2022 Sponsors](https://main--openproblems.netlify.app/competitions/neurips_2022/) and [NeurIPS2021 Sponsors](https://main--openproblems.netlify.app/competitions/neurips_2021/):
![Screenshot from 2023-03-13 12-58-34](https://user-images.githubusercontent.com/553642/224695545-13aafcad-0229-4733-a18d-82a45cf92150.png)

- [ ] [Result cards](https://main--openproblems.netlify.app/results/) don't look as nice:
![Screenshot from 2023-03-13 12-59-272](https://user-images.githubusercontent.com/553642/224696275-4323e319-b8fd-4310-a462-fba59283a20a.png)

Surprisingly, all of the NeurIPS2021 docs pages look quite good! :)

I think all of these are relatively easy to fix, except for the dark mode in FH. 

@scottgigante-immunai WDYT?

**Comment by scottgigante-immunai** [comment]
Oh, I fixed the neurips2021 docs but forgot to include the css in the other neurips pages to fix those sponsor cards.

I think FH in dark mode looks fine -- could be better but imo good enough. Same with the result cards, I think they look fine but could be made better if we make the image responsive. In my opinion we can fix all of these issues today.

**Comment by scottgigante-immunai** [comment]
> * [X]  [FH](https://main--openproblems.netlify.app/results/batch_integration_embed/) labels are not white when not in dark mode

Solved (finally) in https://github.com/openproblems-bio/website/pull/172

> * [ ]  [FH](https://main--openproblems.netlify.app/results/batch_integration_embed/) doesn't have a dark mode:

IMO fine to release as is and improve later.

> * [X]  [NeurIPS2022 Sponsors](https://main--openproblems.netlify.app/competitions/neurips_2022/) and [NeurIPS2021 Sponsors](https://main--openproblems.netlify.app/competitions/neurips_2021/)

Fixed in https://github.com/openproblems-bio/website/pull/184

> * [ ]  [Result cards](https://main--openproblems.netlify.app/results/) don't look as nice:

IMO fine to release as is and improve later.

**Comment by scottgigante-immunai** [comment]
> What about setting the background of the task cards to #323839 when in dark mode?

Sure. Done in #190.

> I think it's still better to not have a Dark mode than to have a Dark mode that makes some aspects of the website less appealing.

I personally think the dark mode as is is already easier on the eye than light mode

**Comment by rcannood** [comment]
Thanks for the extra PR! I'm going to let the remaining issue sink in for a while.
