### ISSUE TITLE
[v2 docs] Move "Add a baseline" from "Contribute" to "Create a new task"

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/website#217]
Adding baselines is a job for task leaders, not for regular community members.

**Comment by rcannood** [comment]
Update: the structure has been changed in such a way that the 'adding baselines' does not need to be moved

![Screenshot from 2023-05-11 09-34-53](https://github.com/openproblems-bio/website/assets/553642/c680c203-9a49-4584-afca-f60472164a90)
