### ISSUE TITLE
Wide tables need scrollbar

### ISSUE THREAD

**Issue by scottgigante** [openproblems-bio/website#24]
Tables with too many columns look squished.

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/8499679/189137527-330ff77c-90d7-42ca-906a-24144f8fbe31.png">

**Comment by scottgigante-immunai** [comment]
@rcannood this is a big issue -- if the table is wider than your browser, you can't see e.g. the method names.

**Comment by dsm-72** [comment]
@rcannood @scottgigante see https://github.com/openproblems-bio/website/pull/81
