### ISSUE TITLE
[poll] control or baseline

### ISSUE THREAD

**Issue by KaiWaldrant** [openproblems-bio/website#247]
I think it's time to figure out what description we are going to use in all the openproblems repos:
:+1: for control method
:-1: for baseline method

@rcannood @scottgigante-immunai @mumichae @mxposed @dburkhardt

**Comment by rcannood** [comment]
Haha. Wouldn't call this an urgent issue, but it definitely needs to be resolved :)

I like being able to talk about positive controls and negative controls, so a :+1: from me.

Reminds me about a conversation with @slobentanzer about defining an ontology for all of the terms and concepts we use to talk about OpenProblems. I think that'd be a great idea.

**Comment by KaiWaldrant** [comment]
I know its not urgent, just a bit of fun on a saturday night :rofl:

**Comment by slobentanzer** [comment]
Still think that would be a cool thing to have. If you don't want to go full-blown semantic web immediately, we could also make drafts using the BioCypher framework (just defining some concepts in the configuration). Happy to brainstorm on that. 

For instance, we could start by manually extending some subclass of [EFO Information Entity](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000030&lang=en&viewMode=All&siblings=false).

**Comment by scottgigante-immunai** [comment]
> I like being able to talk about positive controls and negative controls

Only concern about the term "control" is that in some cases (e.g. batch integration), a single baseline method can be a positive control for one metric, a negative control for another, and be totally irrelevant for a third.

**Comment by scottgigante-immunai** [comment]
I'm not familiar with EFO but `control` would probably be a relationship between a `baseline method` and a `metric` -- so a baseline method is a positive control _for_ a given metric.
