### ISSUE TITLE
Benchmark results tables have double heading

### ISSUE THREAD

**Issue by scottgigante** [openproblems-bio/website#25]
All of the dataset pages have the heading repeated twice.

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/8499679/189137702-28d058fd-eda6-4d62-b7a6-30faa8ae6cee.png">

**Comment by dsm-72** [comment]
@scottgigante Feature not bug. Due to the templating just showing the title in both the page and the partial. In any case this seems to be resolved
