### ISSUE TITLE
DataTable is not a function: Benchmark tables not sorted by rank

### ISSUE THREAD

**Issue by scottgigante** [openproblems-bio/website#26]
The tables should be sorted; currently they are in random order. Do we want to fix this within the website, or in the JSON generation?

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/8499679/189137843-781c8a2b-2e4a-4c9c-b6cb-eb1c142888d4.png">

**Comment by scottgigante-immunai** [comment]
Caused by `Uncaught TypeError: $(...).DataTable is not a function` (thanks to @dsm-72)

**Comment by rcannood** [comment]
Solved by #43
