### ISSUE TITLE
Typo in "design the API"

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/website#265]
This sentence doesn't make sense:

> Generate [reference documentation](https://openproblems.bio/documentation/reference/) are partially automated by having defined these API files.

https://openproblems.bio/documentation/create_task/design_api.html

**Comment by rcannood** [comment]
Already fixed in the main branch, it's just not part of a website release yet.

https://main--openproblems.netlify.app/documentation/create_task/design_api.html
