### ISSUE TITLE
Explain `__merge__` in api file

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/website#266]
The `__merge__` field shows up a number of times in https://openproblems.bio/documentation/create_task/design_api.html and I have no idea what it means.

**Comment by rcannood** [comment]
Please make sure you're using the latest development version of the docs: https://main--openproblems.netlify.app/documentation/create_task/design_api.html. Agreed that the terminology should be explained when first shown in https://main--openproblems.netlify.app/documentation/create_task/design_api.html#step-3 . 

Info about `__merge__` can be found:

* Add a method: https://main--openproblems.netlify.app/documentation/create_component/add_a_method.html#merge__
* Add a control method: https://main--openproblems.netlify.app/documentation/create_component/add_a_control.html#merge__
* Add a metric: https://main--openproblems.netlify.app/documentation/create_component/add_a_metric.html#merge__
* In the FAQ: https://main--openproblems.netlify.app/documentation/more_information/faq#what-does-__merge__-do

It's probably better if this is explained in the concepts page instead ( https://main--openproblems.netlify.app/documentation/create_component/concepts.html ).

**Comment by scottgigante-immunai** [comment]
Gotcha. Those places seem to mostly say "don't worry about it" -- but for defining the API it seems like I actually need to define it?

**Comment by scottgigante-immunai** [comment]
> Please make sure you're using the [latest development version of the docs](https://main--openproblems.netlify.app/documentation/create_task/design_api.html).

Oops (:

**Comment by rcannood** [comment]
Is #267 a good solution to this issue? 

[Preview](https://issue-266-we-dont-talk-about-merge--openproblems.netlify.app/documentation/fundamentals/concepts.html#common-concepts)

**Comment by scottgigante-immunai** [comment]
Perfect, thank you!
